# -*- coding: utf-8 -*-
"""_init__.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Szd6ZJWgEZTDof-zWY1oTyqMFj6OwWCs
"""

"""
EmotionDetection package.
Exposes the `emotion_detector` function as the public API of this package.
"""
from .emotion_detection import emotion_detector

